export const LEAGUE_LOGOS: Record<string, string> = {
  "national-teams": "/logos/leagues/national-teams.png",
  "premier-league": "/logos/leagues/premier-league.png",
  "la-liga": "/logos/leagues/la-liga.png",
  "serie-a": "/logos/leagues/serie-a.png",
  "bundesliga": "/logos/leagues/bundesliga.png",
  "ligue-1": "/logos/leagues/ligue-1.png",
  "brasileirao": "/logos/leagues/brasileirao.png",
  "liga-profesional": "/logos/leagues/liga-profesional.png",
  "mls": "/logos/leagues/mls.png",
  "saudi-pro-league": "/logos/leagues/saudi-pro-league.png",
  "eredivisie": "/logos/leagues/eredivisie.png",
  "liga-mx": "/logos/leagues/liga-mx.png",
  "liga-portugal": "/logos/leagues/liga-portugal.png",
};

export const NATIONAL_TEAM_CRESTS: Record<string, string> = {
  "morocco": "/logos/national-teams/morocco.png",
  "argentina": "/logos/national-teams/argentina.png",
  "brazil": "/logos/national-teams/brazil.png",
  "france": "/logos/national-teams/france.png",
  "germany": "/logos/national-teams/germany.png",
  "spain": "/logos/national-teams/spain.png",
  "england": "/logos/national-teams/england.png",
  "portugal": "/logos/national-teams/portugal.png",
  "italy": "/logos/national-teams/italy.png",
  "netherlands": "/logos/national-teams/netherlands.png",
  "belgium": "/logos/national-teams/belgium.png",
  "japan": "/logos/national-teams/japan.png",
  "croatia": "/logos/national-teams/croatia.png",
  "uruguay": "/logos/national-teams/uruguay.png",
  "colombia": "/logos/national-teams/colombia.png",
  "mexico": "/logos/national-teams/mexico.png",
  "usa": "/logos/national-teams/usa.png",
  "senegal": "/logos/national-teams/senegal.png",
  "nigeria": "/logos/national-teams/nigeria.png",
  "egypt": "/logos/national-teams/egypt.png",
  "algeria": "/logos/national-teams/algeria.png",
  "turkey": "/logos/national-teams/turkey.png",
  "denmark": "/logos/national-teams/denmark.png",
  "poland": "/logos/national-teams/poland.png",
  "cameroon": "/logos/national-teams/cameroon.png",
  "south-korea": "/logos/national-teams/south-korea.png",
  "saudi-arabia": "/logos/national-teams/saudi-arabia.png",
  "canada": "/logos/national-teams/canada.png",
  "australia": "/logos/national-teams/australia.png",
  "ghana": "/logos/national-teams/ghana.png",
  "switzerland": "/logos/national-teams/switzerland.png",
  "scotland": "/logos/national-teams/scotland.png",
  "wales": "/logos/national-teams/wales.png",
  "tunisia": "/logos/national-teams/tunisia.png",
  "ecuador": "/logos/national-teams/ecuador.png",
  "serbia": "/logos/national-teams/serbia.png",
};

export const COUNTRY_FLAGS: { name: string; slug: string; code: string }[] = [
  { name: "Morocco", slug: "morocco", code: "ma" },
  { name: "Argentina", slug: "argentina", code: "ar" },
  { name: "Brazil", slug: "brazil", code: "br" },
  { name: "France", slug: "france", code: "fr" },
  { name: "Germany", slug: "germany", code: "de" },
  { name: "Spain", slug: "spain", code: "es" },
  { name: "England", slug: "england", code: "gb-eng" },
  { name: "Portugal", slug: "portugal", code: "pt" },
  { name: "Italy", slug: "italy", code: "it" },
  { name: "Netherlands", slug: "netherlands", code: "nl" },
  { name: "Belgium", slug: "belgium", code: "be" },
  { name: "Japan", slug: "japan", code: "jp" },
  { name: "Croatia", slug: "croatia", code: "hr" },
  { name: "Uruguay", slug: "uruguay", code: "uy" },
  { name: "Colombia", slug: "colombia", code: "co" },
  { name: "Mexico", slug: "mexico", code: "mx" },
  { name: "USA", slug: "usa", code: "us" },
  { name: "Senegal", slug: "senegal", code: "sn" },
  { name: "Nigeria", slug: "nigeria", code: "ng" },
  { name: "Egypt", slug: "egypt", code: "eg" },
  { name: "Algeria", slug: "algeria", code: "dz" },
  { name: "Turkey", slug: "turkey", code: "tr" },
  { name: "Denmark", slug: "denmark", code: "dk" },
  { name: "Poland", slug: "poland", code: "pl" },
  { name: "Cameroon", slug: "cameroon", code: "cm" },
  { name: "South Korea", slug: "south-korea", code: "kr" },
  { name: "Saudi Arabia", slug: "saudi-arabia", code: "sa" },
  { name: "Canada", slug: "canada", code: "ca" },
  { name: "Australia", slug: "australia", code: "au" },
  { name: "Ghana", slug: "ghana", code: "gh" },
  { name: "Serbia", slug: "serbia", code: "rs" },
  { name: "Switzerland", slug: "switzerland", code: "ch" },
  { name: "Scotland", slug: "scotland", code: "gb-sct" },
  { name: "Wales", slug: "wales", code: "gb-wls" },
  { name: "Tunisia", slug: "tunisia", code: "tn" },
  { name: "Ecuador", slug: "ecuador", code: "ec" },
];

export const BRAND_LOGOS = [
  { name: "Nike", logo: "/logos/brands/nike.svg" },
  { name: "Adidas", logo: "/logos/brands/adidas.svg" },
  { name: "Puma", logo: "/logos/brands/puma.svg" },
  { name: "New Balance", logo: "/logos/brands/new-balance.svg" },
  { name: "Umbro", logo: "/logos/brands/umbro.svg" },
  { name: "Kappa", logo: "/logos/brands/kappa.svg" },
  { name: "Joma", logo: "/logos/brands/joma.svg" },
  { name: "Hummel", logo: "/logos/brands/hummel.svg" },
  { name: "Le Coq Sportif", logo: "/logos/brands/le-coq-sportif.svg" },
];

export const LEAGUES_DATA = [
  {
    name: "World Cup 2026",
    slug: "national-teams",
    teams: [
      "Morocco", "Argentina", "Brazil", "France", "Germany", "Spain",
      "England", "Portugal", "Italy", "Netherlands", "Belgium", "Japan",
      "Croatia", "Uruguay", "Colombia", "Mexico", "USA", "Senegal",
      "Nigeria", "Egypt", "Algeria", "Scotland", "Wales", "Serbia",
      "Switzerland", "Denmark", "Poland", "Cameroon", "Ghana", "South Korea",
      "Canada", "Australia", "Saudi Arabia", "Tunisia", "Ecuador", "Turkey",
    ],
  },
  {
    name: "Premier League",
    slug: "premier-league",
    teams: [
      "Manchester United", "Manchester City", "Arsenal", "Chelsea", "Liverpool",
      "Newcastle United", "Tottenham", "Aston Villa", "Brighton", "Everton",
      "West Ham", "Fulham", "Bournemouth", "Crystal Palace", "Nottingham Forest",
      "Brentford", "Wolverhampton", "Leicester City", "Leeds United", "Burnley",
    ],
  },
  {
    name: "La Liga",
    slug: "la-liga",
    teams: [
      "Real Madrid", "FC Barcelona", "Atletico Madrid", "Real Betis", "Valencia",
      "Villarreal", "Real Sociedad", "Sevilla", "Celta Vigo", "Girona",
      "Espanyol", "Osasuna", "Rayo Vallecano", "Deportivo Alaves", "Granada",
    ],
  },
  {
    name: "Serie A",
    slug: "serie-a",
    teams: [
      "Inter Milan", "AC Milan", "Napoli", "Juventus", "AS Roma",
      "Lazio", "Fiorentina", "Atalanta", "Bologna", "Torino",
      "Venezia", "Como", "Parma", "Genoa", "Cagliari",
    ],
  },
  {
    name: "Bundesliga",
    slug: "bundesliga",
    teams: [
      "Bayern Munich", "Borussia Dortmund", "Bayer Leverkusen", "RB Leipzig",
      "Eintracht Frankfurt", "Wolfsburg", "Stuttgart", "Borussia Monchengladbach",
      "Freiburg", "Union Berlin", "Schalke 04", "Werder Bremen",
    ],
  },
  {
    name: "Ligue 1",
    slug: "ligue-1",
    teams: [
      "Paris Saint-Germain", "Olympique Marseille", "Lyon", "Lille", "Lens",
      "AS Monaco", "Nice", "Rennes", "Strasbourg", "Toulouse", "Brest",
    ],
  },
  {
    name: "Brasileirao",
    slug: "brasileirao",
    teams: [
      "Flamengo", "Corinthians", "Palmeiras", "Sao Paulo", "Santos",
      "Fluminense", "Botafogo", "Vasco da Gama", "Gremio", "Internacional",
      "Cruzeiro", "Atletico Mineiro", "Bahia",
    ],
  },
  {
    name: "Liga Profesional",
    slug: "liga-profesional",
    teams: [
      "Boca Juniors", "River Plate", "Racing", "Independiente", "San Lorenzo",
    ],
  },
  {
    name: "MLS",
    slug: "mls",
    teams: [
      "Inter Miami", "LA Galaxy", "Los Angeles FC", "New York City FC",
      "Atlanta United", "Seattle Sounders", "Austin FC", "Columbus Crew",
    ],
  },
  {
    name: "Saudi Pro League",
    slug: "saudi-pro-league",
    teams: ["Al Nassr", "Al-Hilal", "Al Ittihad", "Al Ahli"],
  },
  {
    name: "Eredivisie",
    slug: "eredivisie",
    teams: ["Ajax", "PSV Eindhoven", "Feyenoord"],
  },
  {
    name: "Liga MX",
    slug: "liga-mx",
    teams: ["Club America", "Chivas Guadalajara", "Cruz Azul", "Tigres", "CF Monterrey"],
  },
  {
    name: "Liga Portugal",
    slug: "liga-portugal",
    teams: ["Benfica", "Porto", "Sporting CP", "Braga"],
  },
];

export const CATEGORIES = [
  { name: "Jerseys", slug: "jersey" },
  { name: "Track Suits", slug: "tracksuit" },
  { name: "Retro Shirts", slug: "retro" },
  { name: "Training", slug: "training" },
  { name: "Shorts", slug: "shorts" },
  { name: "Kids Kit", slug: "kids" },
];

export const SIZES = ["S", "M", "L", "XL", "XXL", "XXXL"];
